### ISSUE TITLE
Fatal TypeError: cannot read property 'output' of undefined 

### ISSUE THREAD

**Issue by dnorton94** [desmarchris/sms-bot#1]
@desmarchris Thanks for this! I was led here by the YouTube video 'Watson Conversation - Integrations Tutorial' However, I am currently running into some issues...

C:\Users\dnort\Desktop\sms-bot>node app.js
Initializing Botkit v0.5.4
info: ** No persistent storage method specified! Data may be lost when process shuts down.
info: *> Listening on port 8000
info: *> Serving webhook endpoint DESKTOP-7T4STH1:8000/sms/receive
TwilioSMSBot is online!
info: => Got a message hook
Fatal TypeError: Cannot read property 'output' of undefined
    at C:\Users\dnort\Desktop\sms-bot\app.js:30:45
    at C:\Users\dnort\Desktop\sms-bot\node_modules\botkit-middleware-watson\lib\middleware\index.js:121:9
    at tryCatcher (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\dnort\Desktop\sms-bot\node_modules\bluebird\js\release\async.js:17:14)

How would you suggest I resolve this?

Thank You

**Comment by ahendo026** [comment]
I am receiving the same error. Please advise.

**Comment by desmarchris** [comment]
can you try taking out the index here? Line 30: `bot.reply(message, message.watsonData.output.text[0]);`

**Comment by Abishek09** [comment]
Hi Chris, great tutorial ! I'm facing the same error. Tried removing the index but it still isn't working.

**Comment by desmarchris** [comment]
Check if your region is using IAM auth rather than standard username;password as well.. I just added a bit of code to `app.js` to use if you are using IAM auth (this was @ahendo026 's issue)

**Comment by Abishek09** [comment]
I'm using the IAM auth. 
I made the changes that you've added in the app.js file but I'm still getting the error.
Could there be any other reason for the error?
Thanks for your response!

**Comment by desmarchris** [comment]
If it's the error above, then the call to Watson is what's not working. Can you share what you are putting in the `url` parameter? (Note, there aren't any API creds that need to be in the URL)

**Comment by Abishek09** [comment]
url:'https://gateway-wdc.watsonplatform.net/assistant/api'
This is the URL parameter in my app.js

Here's how the entire code looks:

'use strict'

require('dotenv').config({silent: true});

var middleware = require('botkit-middleware-watson')({
  iam_apikey:'6S9SCsbZVqAKiRvCW5Tp4lxPCV6ME6WXwqJFMy0UL24E',
  url:'https://gateway-wdc.watsonplatform.net/assistant/api',
  workspace_id:'8eb38102-3595-412c-8266-85d9b25a204c',
  version:'2018-07-10'
});

var TwilioSMSBot = require('botkit-sms');
var controller = TwilioSMSBot({
  account_sid: process.env.ACCOUNT_SID,
  auth_token: process.env.AUTH_TOKEN,
  twilio_number: process.env.TWILIO_NUMBER
});

let bot = controller.spawn({})

controller.setupWebserver('5500', function (err, webserver) {
  if (err) console.log(err)
  controller.createWebhookEndpoints(controller.webserver, bot, function () {
    console.log('TwilioSMSBot is online!');
  })
});

controller.hears(['.*'], 'message_received', function (bot, message) {
  middleware.interpret(bot, message, function(err) {
      bot.reply(message, message.watsonData.output.text[0]);
    })
});

Note: my local server is at port 5500.

**Comment by desmarchris** [comment]
@Abishek09 did you run `npm update` after taking in the IAM code? URL looks fine. Also I would modify that so you aren't sharing your creds :)

**Comment by abhijit-nimbalkar** [comment]
@desmarchris Hey Chris, 
Thanks for the tutorial. I have a question. How can I send the context variable to the watson with a received message from Twilio? Sorry, I could not find any other communication channel to reach you.
Thanks.
